# frozen_string_literal: true

require "lutaml/model"

module Sts
  module NisoSts
    module MmlContent
      # Base class for Content MathML elements
      # Content MathML elements share the MathML namespace
      class Object < Lutaml::Model::Serializable
        xml do
          namespace ::Sts::Namespaces::MathmlNamespace
        end
      end

      # Use autoload for all element classes to avoid circular dependency issues
      autoload :Apply, "#{__dir__}/mml_content/apply"
      autoload :Bind, "#{__dir__}/mml_content/bind"
      autoload :Ci, "#{__dir__}/mml_content/ci"
      autoload :Cn, "#{__dir__}/mml_content/cn"
      autoload :Csymbol, "#{__dir__}/mml_content/csymbol"
      autoload :Cbytes, "#{__dir__}/mml_content/containers"
      autoload :Cerror, "#{__dir__}/mml_content/containers"
      autoload :Cs, "#{__dir__}/mml_content/containers"
      autoload :Share, "#{__dir__}/mml_content/containers"
      autoload :Piecewise, "#{__dir__}/mml_content/containers"
      autoload :Piece, "#{__dir__}/mml_content/containers"
      autoload :Otherwise, "#{__dir__}/mml_content/containers"
      autoload :Plus, "#{__dir__}/mml_content/operators"
      autoload :Minus, "#{__dir__}/mml_content/operators"
      autoload :Times, "#{__dir__}/mml_content/operators"
      autoload :Divide, "#{__dir__}/mml_content/operators"
      autoload :Power, "#{__dir__}/mml_content/operators"
      autoload :Root, "#{__dir__}/mml_content/operators"
      autoload :Abs, "#{__dir__}/mml_content/operators"
      autoload :Quotient, "#{__dir__}/mml_content/operators"
      autoload :Rem, "#{__dir__}/mml_content/operators"
      autoload :Gcd, "#{__dir__}/mml_content/operators"
      autoload :Lcm, "#{__dir__}/mml_content/operators"
      autoload :Factorial, "#{__dir__}/mml_content/operators"
      autoload :Conjugate, "#{__dir__}/mml_content/operators"
      autoload :Arg, "#{__dir__}/mml_content/operators"
      autoload :Real, "#{__dir__}/mml_content/operators"
      autoload :Imaginary, "#{__dir__}/mml_content/operators"
      autoload :Floor, "#{__dir__}/mml_content/operators"
      autoload :Ceiling, "#{__dir__}/mml_content/operators"
      autoload :Exp, "#{__dir__}/mml_content/operators"
      autoload :Ln, "#{__dir__}/mml_content/operators"
      autoload :Log, "#{__dir__}/mml_content/operators"
      autoload :Eq, "#{__dir__}/mml_content/relations"
      autoload :Neq, "#{__dir__}/mml_content/relations"
      autoload :Lt, "#{__dir__}/mml_content/relations"
      autoload :Gt, "#{__dir__}/mml_content/relations"
      autoload :Leq, "#{__dir__}/mml_content/relations"
      autoload :Geq, "#{__dir__}/mml_content/relations"
      autoload :Approx, "#{__dir__}/mml_content/relations"
      autoload :Factorof, "#{__dir__}/mml_content/relations"
      autoload :Tendsto, "#{__dir__}/mml_content/relations"
      autoload :Implies, "#{__dir__}/mml_content/relations"
      autoload :Equivalent, "#{__dir__}/mml_content/relations"
      autoload :Bvar, "#{__dir__}/mml_content/qualifiers"
      autoload :Domainofapplication, "#{__dir__}/mml_content/qualifiers"
      autoload :Condition, "#{__dir__}/mml_content/qualifiers"
      autoload :Lowlimit, "#{__dir__}/mml_content/qualifiers"
      autoload :Uplimit, "#{__dir__}/mml_content/qualifiers"
      autoload :Degree, "#{__dir__}/mml_content/qualifiers"
      autoload :Momentabout, "#{__dir__}/mml_content/qualifiers"
      autoload :Logbase, "#{__dir__}/mml_content/qualifiers"
      autoload :Lambda, "#{__dir__}/mml_content/functional"
      autoload :And, "#{__dir__}/mml_content/functional"
      autoload :Or, "#{__dir__}/mml_content/functional"
      autoload :Xor, "#{__dir__}/mml_content/functional"
      autoload :Not, "#{__dir__}/mml_content/functional"
      autoload :Forall, "#{__dir__}/mml_content/functional"
      autoload :Exists, "#{__dir__}/mml_content/functional"
      autoload :Ident, "#{__dir__}/mml_content/functional"
      autoload :Inverse, "#{__dir__}/mml_content/functional"
      autoload :Compose, "#{__dir__}/mml_content/functional"
      autoload :Domain, "#{__dir__}/mml_content/functional"
      autoload :Codomain, "#{__dir__}/mml_content/functional"
      autoload :Image, "#{__dir__}/mml_content/functional"
      autoload :Integers, "#{__dir__}/mml_content/constants"
      autoload :Reals, "#{__dir__}/mml_content/constants"
      autoload :Rationals, "#{__dir__}/mml_content/constants"
      autoload :Naturalnumbers, "#{__dir__}/mml_content/constants"
      autoload :Complexes, "#{__dir__}/mml_content/constants"
      autoload :Primes, "#{__dir__}/mml_content/constants"
      autoload :Emptyset, "#{__dir__}/mml_content/constants"
      autoload :Exponentiale, "#{__dir__}/mml_content/constants"
      autoload :Imaginaryi, "#{__dir__}/mml_content/constants"
      autoload :Notanumber, "#{__dir__}/mml_content/constants"
      autoload :True, "#{__dir__}/mml_content/constants"
      autoload :False, "#{__dir__}/mml_content/constants"
      autoload :Pi, "#{__dir__}/mml_content/constants"
      autoload :Eulergamma, "#{__dir__}/mml_content/constants"
      autoload :Infinity, "#{__dir__}/mml_content/constants"
      autoload :Set, "#{__dir__}/mml_content/sets"
      autoload :List, "#{__dir__}/mml_content/sets"
      autoload :Union, "#{__dir__}/mml_content/sets"
      autoload :Intersect, "#{__dir__}/mml_content/sets"
      autoload :Setdiff, "#{__dir__}/mml_content/sets"
      autoload :Cartesianproduct, "#{__dir__}/mml_content/sets"
      autoload :Card, "#{__dir__}/mml_content/sets"
      autoload :Vector, "#{__dir__}/mml_content/linear_algebra"
      autoload :Matrix, "#{__dir__}/mml_content/linear_algebra"
      autoload :Matrixrow, "#{__dir__}/mml_content/linear_algebra"
      autoload :Determinant, "#{__dir__}/mml_content/linear_algebra"
      autoload :Transpose, "#{__dir__}/mml_content/linear_algebra"
      autoload :Vectorproduct, "#{__dir__}/mml_content/linear_algebra"
      autoload :Scalarproduct, "#{__dir__}/mml_content/linear_algebra"
      autoload :Outerproduct, "#{__dir__}/mml_content/linear_algebra"
      autoload :Selector, "#{__dir__}/mml_content/linear_algebra"
      autoload :Int, "#{__dir__}/mml_content/calculus"
      autoload :Diff, "#{__dir__}/mml_content/calculus"
      autoload :Partialdiff, "#{__dir__}/mml_content/calculus"
      autoload :Grad, "#{__dir__}/mml_content/calculus"
      autoload :Divergence, "#{__dir__}/mml_content/calculus"
      autoload :Curl, "#{__dir__}/mml_content/calculus"
      autoload :Laplacian, "#{__dir__}/mml_content/calculus"
      autoload :Sum, "#{__dir__}/mml_content/calculus"
      autoload :Product, "#{__dir__}/mml_content/calculus"
      autoload :Limit, "#{__dir__}/mml_content/calculus"
      autoload :Mean, "#{__dir__}/mml_content/statistics"
      autoload :Sdev, "#{__dir__}/mml_content/statistics"
      autoload :Variance, "#{__dir__}/mml_content/statistics"
      autoload :Median, "#{__dir__}/mml_content/statistics"
      autoload :Mode, "#{__dir__}/mml_content/statistics"
      autoload :Moment, "#{__dir__}/mml_content/statistics"
      autoload :Sin, "#{__dir__}/mml_content/trigonometry"
      autoload :Cos, "#{__dir__}/mml_content/trigonometry"
      autoload :Tan, "#{__dir__}/mml_content/trigonometry"
      autoload :Sec, "#{__dir__}/mml_content/trigonometry"
      autoload :Csc, "#{__dir__}/mml_content/trigonometry"
      autoload :Cot, "#{__dir__}/mml_content/trigonometry"
      autoload :Sinh, "#{__dir__}/mml_content/trigonometry"
      autoload :Cosh, "#{__dir__}/mml_content/trigonometry"
      autoload :Tanh, "#{__dir__}/mml_content/trigonometry"
      autoload :Sech, "#{__dir__}/mml_content/trigonometry"
      autoload :Csch, "#{__dir__}/mml_content/trigonometry"
      autoload :Coth, "#{__dir__}/mml_content/trigonometry"
      autoload :Arcsin, "#{__dir__}/mml_content/trigonometry"
      autoload :Arccos, "#{__dir__}/mml_content/trigonometry"
      autoload :Arctan, "#{__dir__}/mml_content/trigonometry"
      autoload :Arccosh, "#{__dir__}/mml_content/trigonometry"
      autoload :Arcsinh, "#{__dir__}/mml_content/trigonometry"
      autoload :Arctanh, "#{__dir__}/mml_content/trigonometry"
      autoload :Arccoth, "#{__dir__}/mml_content/trigonometry"
      autoload :Arccsch, "#{__dir__}/mml_content/trigonometry"
      autoload :Arcsech, "#{__dir__}/mml_content/trigonometry"
    end
  end
end
