inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

# local repo-specific modifications
# ...

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'lib/sts/mapper.rb'
    - 'vendor/**/*'
