inherit_from:
  - .rubocop_todo.yml
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

# local repo-specific modifications
# ...

Metrics/BlockLength:
  Max: 35

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'lib/sts/mapper.rb'
    - 'vendor/**/*'
