# frozen_string_literal: true

require "mml"

module Sts
  module IsoSts
    autoload :Standard, "#{__dir__}/iso_sts/standard"
    autoload :Front, "#{__dir__}/iso_sts/front"
    autoload :Body, "#{__dir__}/iso_sts/body"
    autoload :Back, "#{__dir__}/iso_sts/back"

    # Metadata
    autoload :IsoMeta, "#{__dir__}/iso_sts/iso_meta"
    autoload :RegMeta, "#{__dir__}/iso_sts/reg_meta"
    autoload :NatMeta, "#{__dir__}/iso_sts/nat_meta"
    autoload :TitleWrap, "#{__dir__}/iso_sts/title_wrap"
    autoload :TitleIntro, "#{__dir__}/iso_sts/title_intro"
    autoload :TitleMain, "#{__dir__}/iso_sts/title_main"
    autoload :TitleCompl, "#{__dir__}/iso_sts/title_compl"
    autoload :TitleFull, "#{__dir__}/iso_sts/title_full"
    autoload :DocumentIdentification,
             "#{__dir__}/iso_sts/document_identification"
    autoload :StandardIdentification,
             "#{__dir__}/iso_sts/standard_identification"
    autoload :Permissions, "#{__dir__}/iso_sts/permissions"
    autoload :CopyrightStatement, "#{__dir__}/iso_sts/copyright_statement"
    autoload :CopyrightYear, "#{__dir__}/iso_sts/copyright_year"
    autoload :CopyrightHolder, "#{__dir__}/iso_sts/copyright_holder"
    autoload :PageCount, "#{__dir__}/iso_sts/page_count"
    autoload :StandardCrossReference,
             "#{__dir__}/iso_sts/standard_cross_reference"
    autoload :Edition, "#{__dir__}/iso_sts/edition"
    autoload :Language, "#{__dir__}/iso_sts/language"
    autoload :DocRef, "#{__dir__}/iso_sts/doc_ref"
    autoload :ReleaseDate, "#{__dir__}/iso_sts/release_date"
    autoload :CommRef, "#{__dir__}/iso_sts/comm_ref"
    autoload :Secretariat, "#{__dir__}/iso_sts/secretariat"
    autoload :MetaDate, "#{__dir__}/iso_sts/meta_date"
    autoload :ContentLanguage, "#{__dir__}/iso_sts/content_language"
    autoload :StandardRef, "#{__dir__}/iso_sts/standard_ref"
    autoload :WiNumber, "#{__dir__}/iso_sts/wi_number"
    autoload :Originator, "#{__dir__}/iso_sts/originator"
    autoload :DocType, "#{__dir__}/iso_sts/doc_type"
    autoload :DocNumber, "#{__dir__}/iso_sts/doc_number"
    autoload :PartNumber, "#{__dir__}/iso_sts/part_number"
    autoload :Version, "#{__dir__}/iso_sts/version"
    autoload :SupplType, "#{__dir__}/iso_sts/suppl_type"
    autoload :SupplNumber, "#{__dir__}/iso_sts/suppl_number"
    autoload :SupplVersion, "#{__dir__}/iso_sts/suppl_version"
    autoload :Urn, "#{__dir__}/iso_sts/urn"
    autoload :Sdo, "#{__dir__}/iso_sts/sdo"
    autoload :ProjId, "#{__dir__}/iso_sts/proj_id"
    autoload :ReleaseVersion, "#{__dir__}/iso_sts/release_version"
    autoload :Ics, "#{__dir__}/iso_sts/ics"
    autoload :Year, "#{__dir__}/iso_sts/year"
    autoload :PubDate, "#{__dir__}/iso_sts/pub_date"
    autoload :ReleaseVersionId, "#{__dir__}/iso_sts/release_version_id"
    autoload :IsProof, "#{__dir__}/iso_sts/is_proof"
    autoload :AltText, "#{__dir__}/iso_sts/alt_text"
    autoload :LongDesc, "#{__dir__}/iso_sts/long_desc"
    autoload :TexMath, "#{__dir__}/iso_sts/tex_math"
    autoload :PubId, "#{__dir__}/iso_sts/pub_id"
    autoload :Volume, "#{__dir__}/iso_sts/volume"
    autoload :Issue, "#{__dir__}/iso_sts/issue"
    autoload :Fpage, "#{__dir__}/iso_sts/fpage"
    autoload :Lpage, "#{__dir__}/iso_sts/lpage"
    autoload :PageRange, "#{__dir__}/iso_sts/page_range"

    # Section elements
    autoload :Sec, "#{__dir__}/iso_sts/sec"
    autoload :TermSec, "#{__dir__}/iso_sts/term_sec"
    autoload :NonNormativeNote, "#{__dir__}/iso_sts/non_normative_note"
    autoload :NonNormativeExample, "#{__dir__}/iso_sts/non_normative_example"

    # Inline/block elements
    autoload :Paragraph, "#{__dir__}/iso_sts/paragraph"
    autoload :InlineFormula, "#{__dir__}/iso_sts/inline_formula"
    autoload :DispFormula, "#{__dir__}/iso_sts/disp_formula"
    autoload :Std, "#{__dir__}/iso_sts/std"
    autoload :StdRef, "#{__dir__}/iso_sts/std_ref"
    autoload :StyledContent, "#{__dir__}/iso_sts/styled_content"
    autoload :Preformat, "#{__dir__}/iso_sts/preformat"
    autoload :Xref, "#{__dir__}/iso_sts/xref"
    autoload :ExtLink, "#{__dir__}/iso_sts/ext_link"
    autoload :Break, "#{__dir__}/iso_sts/break"
    autoload :Sub, "#{__dir__}/iso_sts/sub"
    autoload :Sup, "#{__dir__}/iso_sts/sup"
    autoload :Label, "#{__dir__}/iso_sts/label"
    autoload :Title, "#{__dir__}/iso_sts/title"
    autoload :Bold, "#{__dir__}/iso_sts/bold"
    autoload :Italic, "#{__dir__}/iso_sts/italic"
    autoload :Monospace, "#{__dir__}/iso_sts/monospace"
    autoload :NamedContent, "#{__dir__}/iso_sts/named_content"
    autoload :Sc, "#{__dir__}/iso_sts/sc"
    autoload :Strike, "#{__dir__}/iso_sts/strike"
    autoload :Underline, "#{__dir__}/iso_sts/underline"
    autoload :Uri, "#{__dir__}/iso_sts/uri"

    # Shared model foundations
    autoload :Abbrev, "#{__dir__}/iso_sts/abbrev"
    autoload :Annotation, "#{__dir__}/iso_sts/annotation"
    autoload :Country, "#{__dir__}/iso_sts/country"
    autoload :Day, "#{__dir__}/iso_sts/day"
    autoload :Etal, "#{__dir__}/iso_sts/etal"
    autoload :Fax, "#{__dir__}/iso_sts/fax"
    autoload :InlineGraphic, "#{__dir__}/iso_sts/inline_graphic"
    autoload :Institution, "#{__dir__}/iso_sts/institution"
    autoload :MilestoneEnd, "#{__dir__}/iso_sts/milestone_end"
    autoload :MilestoneStart, "#{__dir__}/iso_sts/milestone_start"
    autoload :Month, "#{__dir__}/iso_sts/month"
    autoload :Num, "#{__dir__}/iso_sts/num"
    autoload :ObjectId, "#{__dir__}/iso_sts/object_id"
    autoload :Phone, "#{__dir__}/iso_sts/phone"
    autoload :Season, "#{__dir__}/iso_sts/season"

    # Recursive content closure
    autoload :AddrLine, "#{__dir__}/iso_sts/addr_line"
    autoload :Address, "#{__dir__}/iso_sts/address"
    autoload :Aff, "#{__dir__}/iso_sts/aff"
    autoload :AffAlternatives, "#{__dir__}/iso_sts/aff_alternatives"
    autoload :Alternatives, "#{__dir__}/iso_sts/alternatives"
    autoload :Anonymous, "#{__dir__}/iso_sts/anonymous"
    autoload :ArticleTitle, "#{__dir__}/iso_sts/article_title"
    autoload :Attrib, "#{__dir__}/iso_sts/attrib"
    autoload :AuthorComment, "#{__dir__}/iso_sts/author_comment"
    autoload :Bio, "#{__dir__}/iso_sts/bio"
    autoload :BoxedText, "#{__dir__}/iso_sts/boxed_text"
    autoload :ChapterTitle, "#{__dir__}/iso_sts/chapter_title"
    autoload :ChemStruct, "#{__dir__}/iso_sts/chem_struct"
    autoload :ChemStructWrap, "#{__dir__}/iso_sts/chem_struct_wrap"
    autoload :Collab, "#{__dir__}/iso_sts/collab"
    autoload :Comment, "#{__dir__}/iso_sts/comment"
    autoload :ConfDate, "#{__dir__}/iso_sts/conf_date"
    autoload :ConfLoc, "#{__dir__}/iso_sts/conf_loc"
    autoload :ConfName, "#{__dir__}/iso_sts/conf_name"
    autoload :ConfSponsor, "#{__dir__}/iso_sts/conf_sponsor"
    autoload :Contrib, "#{__dir__}/iso_sts/contrib"
    autoload :ContribGroup, "#{__dir__}/iso_sts/contrib_group"
    autoload :Date, "#{__dir__}/iso_sts/date"
    autoload :DateInCitation, "#{__dir__}/iso_sts/date_in_citation"
    autoload :Degrees, "#{__dir__}/iso_sts/degrees"
    autoload :DispFormulaGroup, "#{__dir__}/iso_sts/disp_formula_group"
    autoload :DispQuote, "#{__dir__}/iso_sts/disp_quote"
    autoload :ElementCitation, "#{__dir__}/iso_sts/element_citation"
    autoload :ElocationId, "#{__dir__}/iso_sts/elocation_id"
    autoload :FigGroup, "#{__dir__}/iso_sts/fig_group"
    autoload :GivenNames, "#{__dir__}/iso_sts/given_names"
    autoload :Glossary, "#{__dir__}/iso_sts/glossary"
    autoload :GlyphData, "#{__dir__}/iso_sts/glyph_data"
    autoload :GlyphRef, "#{__dir__}/iso_sts/glyph_ref"
    autoload :Gov, "#{__dir__}/iso_sts/gov"
    autoload :InlineSupplementaryMaterial,
             "#{__dir__}/iso_sts/inline_supplementary_material"
    autoload :Isbn, "#{__dir__}/iso_sts/isbn"
    autoload :Issn, "#{__dir__}/iso_sts/issn"
    autoload :IssueId, "#{__dir__}/iso_sts/issue_id"
    autoload :IssuePart, "#{__dir__}/iso_sts/issue_part"
    autoload :IssueTitle, "#{__dir__}/iso_sts/issue_title"
    autoload :JournalId, "#{__dir__}/iso_sts/journal_id"
    autoload :Media, "#{__dir__}/iso_sts/media"
    autoload :Name, "#{__dir__}/iso_sts/name"
    autoload :NameAlternatives, "#{__dir__}/iso_sts/name_alternatives"
    autoload :OnBehalfOf, "#{__dir__}/iso_sts/on_behalf_of"
    autoload :Overline, "#{__dir__}/iso_sts/overline"
    autoload :PartTitle, "#{__dir__}/iso_sts/part_title"
    autoload :Patent, "#{__dir__}/iso_sts/patent"
    autoload :PersonGroup, "#{__dir__}/iso_sts/person_group"
    autoload :Prefix, "#{__dir__}/iso_sts/prefix"
    autoload :PrivateChar, "#{__dir__}/iso_sts/private_char"
    autoload :RelatedArticle, "#{__dir__}/iso_sts/related_article"
    autoload :RelatedObject, "#{__dir__}/iso_sts/related_object"
    autoload :Role, "#{__dir__}/iso_sts/role"
    autoload :Roman, "#{__dir__}/iso_sts/roman"
    autoload :SansSerif, "#{__dir__}/iso_sts/sans_serif"
    autoload :Series, "#{__dir__}/iso_sts/series"
    autoload :Size, "#{__dir__}/iso_sts/size"
    autoload :Source, "#{__dir__}/iso_sts/source"
    autoload :Speaker, "#{__dir__}/iso_sts/speaker"
    autoload :Speech, "#{__dir__}/iso_sts/speech"
    autoload :Statement, "#{__dir__}/iso_sts/statement"
    autoload :StringName, "#{__dir__}/iso_sts/string_name"
    autoload :Subtitle, "#{__dir__}/iso_sts/subtitle"
    autoload :Suffix, "#{__dir__}/iso_sts/suffix"
    autoload :Supplement, "#{__dir__}/iso_sts/supplement"
    autoload :SupplementaryMaterial, "#{__dir__}/iso_sts/supplementary_material"
    autoload :Surname, "#{__dir__}/iso_sts/surname"
    autoload :TableWrapGroup, "#{__dir__}/iso_sts/table_wrap_group"
    autoload :Target, "#{__dir__}/iso_sts/target"
    autoload :TextualForm, "#{__dir__}/iso_sts/textual_form"
    autoload :TransSource, "#{__dir__}/iso_sts/trans_source"
    autoload :TransTitle, "#{__dir__}/iso_sts/trans_title"
    autoload :VerseGroup, "#{__dir__}/iso_sts/verse_group"
    autoload :VerseLine, "#{__dir__}/iso_sts/verse_line"
    autoload :VolumeId, "#{__dir__}/iso_sts/volume_id"
    autoload :VolumeSeries, "#{__dir__}/iso_sts/volume_series"

    # Remaining namespace closure
    autoload :AwardId, "#{__dir__}/iso_sts/award_id"
    autoload :CustomMeta, "#{__dir__}/iso_sts/custom_meta"
    autoload :CustomMetaGroup, "#{__dir__}/iso_sts/custom_meta_group"
    autoload :FundingSource, "#{__dir__}/iso_sts/funding_source"
    autoload :License, "#{__dir__}/iso_sts/license"
    autoload :LicenseP, "#{__dir__}/iso_sts/license_p"
    autoload :MetaName, "#{__dir__}/iso_sts/meta_name"
    autoload :MetaValue, "#{__dir__}/iso_sts/meta_value"
    autoload :OpenAccess, "#{__dir__}/iso_sts/open_access"
    autoload :Price, "#{__dir__}/iso_sts/price"
    autoload :TermDisplay, "#{__dir__}/iso_sts/term_display"
    autoload :TermHead, "#{__dir__}/iso_sts/term_head"

    # List elements
    autoload :List, "#{__dir__}/iso_sts/list"
    autoload :ListItem, "#{__dir__}/iso_sts/list_item"
    autoload :DefList, "#{__dir__}/iso_sts/def_list"
    autoload :DefItem, "#{__dir__}/iso_sts/def_item"
    autoload :Term, "#{__dir__}/iso_sts/term"
    autoload :Def, "#{__dir__}/iso_sts/def"

    # Table elements
    autoload :TableWrap, "#{__dir__}/iso_sts/table_wrap"
    autoload :Table, "#{__dir__}/iso_sts/table"
    autoload :Thead, "#{__dir__}/iso_sts/thead"
    autoload :Tbody, "#{__dir__}/iso_sts/tbody"
    autoload :Tfoot, "#{__dir__}/iso_sts/tfoot"
    autoload :Tr, "#{__dir__}/iso_sts/tr"
    autoload :Th, "#{__dir__}/iso_sts/th"
    autoload :Td, "#{__dir__}/iso_sts/td"
    autoload :Col, "#{__dir__}/iso_sts/col"
    autoload :Colgroup, "#{__dir__}/iso_sts/colgroup"
    autoload :Caption, "#{__dir__}/iso_sts/caption"
    autoload :TableWrapFoot, "#{__dir__}/iso_sts/table_wrap_foot"
    autoload :Array, "#{__dir__}/iso_sts/array"

    # Figure/graphic
    autoload :Fig, "#{__dir__}/iso_sts/fig"
    autoload :Graphic, "#{__dir__}/iso_sts/graphic"

    # Reference elements
    autoload :Email, "#{__dir__}/iso_sts/email"
    autoload :MixedCitation, "#{__dir__}/iso_sts/mixed_citation"
    autoload :Publisher, "#{__dir__}/iso_sts/publisher"
    autoload :PublisherLoc, "#{__dir__}/iso_sts/publisher_loc"
    autoload :PublisherName, "#{__dir__}/iso_sts/publisher_name"
    autoload :Ref, "#{__dir__}/iso_sts/ref"
    autoload :RefList, "#{__dir__}/iso_sts/ref_list"

    # Back matter
    autoload :AppGroup, "#{__dir__}/iso_sts/app_group"
    autoload :App, "#{__dir__}/iso_sts/app"
    autoload :AnnexType, "#{__dir__}/iso_sts/annex_type"
    autoload :FnGroup, "#{__dir__}/iso_sts/fn_group"
    autoload :Fn, "#{__dir__}/iso_sts/fn"
  end
end
