# frozen_string_literal: true

module Sts
  module NisoSts
    autoload :Adoption, "#{__dir__}/niso_sts/adoption"
    autoload :AdoptionFront, "#{__dir__}/niso_sts/adoption_front"
    autoload :App, "#{__dir__}/niso_sts/app"
    autoload :AppGroup, "#{__dir__}/niso_sts/app_group"
    autoload :Back, "#{__dir__}/niso_sts/back"
    autoload :Body, "#{__dir__}/niso_sts/body"
    autoload :Caption, "#{__dir__}/niso_sts/caption"
    autoload :CustomMeta, "#{__dir__}/niso_sts/custom_meta"
    autoload :CustomMetaGroup, "#{__dir__}/niso_sts/custom_meta_group"
    autoload :Def, "#{__dir__}/niso_sts/def"
    autoload :DefItem, "#{__dir__}/niso_sts/def_item"
    autoload :DefList, "#{__dir__}/niso_sts/def_list"
    autoload :DisplayFormula, "#{__dir__}/niso_sts/display_formula"
    autoload :DocumentIdentification,
             "#{__dir__}/niso_sts/document_identification"
    autoload :ExtLink, "#{__dir__}/niso_sts/ext_link"
    autoload :Figure, "#{__dir__}/niso_sts/figure"
    autoload :Fn, "#{__dir__}/niso_sts/fn"
    autoload :FnGroup, "#{__dir__}/niso_sts/fn_group"
    autoload :Front, "#{__dir__}/niso_sts/front"
    autoload :Graphic, "#{__dir__}/niso_sts/graphic"
    autoload :InlineFormula, "#{__dir__}/niso_sts/inline_formula"
    autoload :Label, "#{__dir__}/niso_sts/label"
    autoload :List, "#{__dir__}/niso_sts/list"
    autoload :ListItem, "#{__dir__}/niso_sts/list_item"
    autoload :MetadataIso, "#{__dir__}/niso_sts/metadata_iso"
    autoload :MetadataStd, "#{__dir__}/niso_sts/metadata_std"
    autoload :MetaDate, "#{__dir__}/niso_sts/meta_date"
    autoload :MetaNote, "#{__dir__}/niso_sts/meta_note"
    autoload :MixedCitation, "#{__dir__}/niso_sts/mixed_citation"
    autoload :NamedContent, "#{__dir__}/niso_sts/named_content"
    autoload :NonNormativeExample, "#{__dir__}/niso_sts/non_normative_example"
    autoload :NonNormativeNote, "#{__dir__}/niso_sts/non_normative_note"
    autoload :ObjectId, "#{__dir__}/niso_sts/object_id"
    autoload :PageCount, "#{__dir__}/niso_sts/page_count"
    autoload :Paragraph, "#{__dir__}/niso_sts/paragraph"
    autoload :Permissions, "#{__dir__}/niso_sts/permissions"
    autoload :Reference, "#{__dir__}/niso_sts/reference"
    autoload :ReferenceList, "#{__dir__}/niso_sts/reference_list"
    autoload :ReferenceStandard, "#{__dir__}/niso_sts/reference_standard"
    autoload :Section, "#{__dir__}/niso_sts/section"
    autoload :SectionArray, "#{__dir__}/niso_sts/section_array"
    autoload :Standard, "#{__dir__}/niso_sts/standard"
    autoload :StandardIdentification,
             "#{__dir__}/niso_sts/standard_identification"
    autoload :StandardRef, "#{__dir__}/niso_sts/standard_ref"
    autoload :StdCrossReference, "#{__dir__}/niso_sts/std_cross_reference"
    autoload :StdId, "#{__dir__}/niso_sts/std_id"
    autoload :StdIdGroup, "#{__dir__}/niso_sts/std_id_group"
    autoload :Term, "#{__dir__}/niso_sts/term"
    autoload :TermDisplay, "#{__dir__}/niso_sts/term_display"
    autoload :TermSection, "#{__dir__}/niso_sts/term_section"
    autoload :Title, "#{__dir__}/niso_sts/title"
    autoload :TitleCompl, "#{__dir__}/niso_sts/title_compl"
    autoload :TitleFull, "#{__dir__}/niso_sts/title_full"
    autoload :TitleWrap, "#{__dir__}/niso_sts/title_wrap"
  end
end
