# frozen_string_literal: true

module Sts
  module TbxIsoTml
    autoload :Bold, "#{__dir__}/tbx_iso_tml/bold"
    autoload :Caption, "#{__dir__}/tbx_iso_tml/caption"
    autoload :Col, "#{__dir__}/tbx_iso_tml/col"
    autoload :CrossReference, "#{__dir__}/tbx_iso_tml/cross_reference"
    autoload :Definition, "#{__dir__}/tbx_iso_tml/definition"
    autoload :EntailedTerm, "#{__dir__}/tbx_iso_tml/entailed_term"
    autoload :Example, "#{__dir__}/tbx_iso_tml/example"
    autoload :ExternalGraphic, "#{__dir__}/tbx_iso_tml/external_graphic"
    autoload :ExternalSource, "#{__dir__}/tbx_iso_tml/external_source"
    autoload :Fn, "#{__dir__}/tbx_iso_tml/fn"
    autoload :FnGroup, "#{__dir__}/tbx_iso_tml/fn_group"
    autoload :GeographicalUsage, "#{__dir__}/tbx_iso_tml/geographical_usage"
    autoload :GrammaticalGender, "#{__dir__}/tbx_iso_tml/grammatical_gender"
    autoload :GrammaticalNumber, "#{__dir__}/tbx_iso_tml/grammatical_number"
    autoload :Italic, "#{__dir__}/tbx_iso_tml/italic"
    autoload :LangSet, "#{__dir__}/tbx_iso_tml/lang_set"
    autoload :Math, "#{__dir__}/tbx_iso_tml/math"
    autoload :Mfenced, "#{__dir__}/tbx_iso_tml/mfenced"
    autoload :Mfrac, "#{__dir__}/tbx_iso_tml/mfrac"
    autoload :Mi, "#{__dir__}/tbx_iso_tml/mi"
    autoload :Mrow, "#{__dir__}/tbx_iso_tml/mrow"
    autoload :Mspace, "#{__dir__}/tbx_iso_tml/mspace"
    autoload :Mstyle, "#{__dir__}/tbx_iso_tml/mstyle"
    autoload :Msub, "#{__dir__}/tbx_iso_tml/msub"
    autoload :Msup, "#{__dir__}/tbx_iso_tml/msup"
    autoload :Munder, "#{__dir__}/tbx_iso_tml/munder"
    autoload :Munderover, "#{__dir__}/tbx_iso_tml/munderover"
    autoload :NormativeAuthorization,
             "#{__dir__}/tbx_iso_tml/normative_authorization"
    autoload :Note, "#{__dir__}/tbx_iso_tml/note"
    autoload :PartOfSpeech, "#{__dir__}/tbx_iso_tml/part_of_speech"
    autoload :Pronunciation, "#{__dir__}/tbx_iso_tml/pronunciation"
    autoload :See, "#{__dir__}/tbx_iso_tml/see"
    autoload :Semantics, "#{__dir__}/tbx_iso_tml/semantics"
    autoload :Source, "#{__dir__}/tbx_iso_tml/source"
    autoload :SubjectField, "#{__dir__}/tbx_iso_tml/subject_field"
    autoload :Sup, "#{__dir__}/tbx_iso_tml/sup"
    autoload :Table, "#{__dir__}/tbx_iso_tml/table"
    autoload :TableBreak, "#{__dir__}/tbx_iso_tml/table_break"
    autoload :TableWrap, "#{__dir__}/tbx_iso_tml/table_wrap"
    autoload :TableWrapFoot, "#{__dir__}/tbx_iso_tml/table_wrap_foot"
    autoload :Tbody, "#{__dir__}/tbx_iso_tml/tbody"
    autoload :Td, "#{__dir__}/tbx_iso_tml/td"
    autoload :Term, "#{__dir__}/tbx_iso_tml/term"
    autoload :TermEntry, "#{__dir__}/tbx_iso_tml/term_entry"
    autoload :TermInformationGroup,
             "#{__dir__}/tbx_iso_tml/term_information_group"
    autoload :TermType, "#{__dir__}/tbx_iso_tml/term_type"
    autoload :Th, "#{__dir__}/tbx_iso_tml/th"
    autoload :Thead, "#{__dir__}/tbx_iso_tml/thead"
    autoload :Tfoot, "#{__dir__}/tbx_iso_tml/tfoot"
    autoload :Colgroup, "#{__dir__}/tbx_iso_tml/colgroup"
    autoload :Tr, "#{__dir__}/tbx_iso_tml/tr"
    autoload :Xref, "#{__dir__}/tbx_iso_tml/xref"
  end
end
